### ISSUE TITLE
Do you have plan to support Carousel component ? 

### ISSUE THREAD

**Issue by duythang** [cristijora/vue-light-bootstrap-dashboard#13]
Great work ! 
I am looking for Carousel component in your dashboard.
Hope see it soon

**Comment by cristijora** [comment]
Sorry for the long wait @duythang 
Unfortunately, this version won't contain a carousel component. It's a pretty limited version because it's free.

I can suggest several options though:
- http://element.eleme.io/#/en-US/component/carousel
- https://github.com/surmon-china/vue-awesome-swiper
- https://ssense.github.io/vue-carousel/

Should be fairly easy to integrate any of those :)
